// This file is generated by Slice Machine. Update with care!

import Forms from './Forms';
import Game from './Game';
import Hero from './Hero';
import Modal from './Modal';
import Test from './Test';

export {
	Forms,
	Game,
	Hero,
	Modal,
	Test,
};

export const components = {
	forms: Forms,
	game: Game,
	hero: Hero,
	modal: Modal,
	test: Test,
};
